//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Jass {

	public static class Core {

		public static List<Type> Classes = new List<Type>();

		public static void RegisterClass(Type type) {
			Console.WriteLine(string.Format("Register Class: {0}", type.ToString()));
			Classes.Add(type);
		}

	}

}

