//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.IO;

namespace Jass {

	public class JassReader : IDisposable {

		public JassReader() {
		
		}

		public void Read(string file) {
			Console.WriteLine(string.Format("Read file: {0}", file));
			string result = null;
			try {
				result = File.ReadAllText(file);
			} catch (Exception exp) {
				Console.WriteLine(string.Format("File not exist {0}\n{1}", file, exp.Message));
			}
			if (result!=null) {
				Parse(result);
			}
		}

		public void Dispose() {

		}

		private void Parse(string file) {

		}

	}
}

