//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.IO;

namespace Jass {

	public class JassReader : IDisposable {

		private int _index;
		private string _content;

		public int Length {
			get { return _content.Length; }
		}

		//contructor
		public JassReader() {
		
		}

		//destructor
		~JassReader() {
			Dispose(false);
		}

		//read file
		public void Read(string file) {
			Log.Add(string.Format("Read file: {0}", file), ConsoleColor.Blue);
			try {
				_content = File.ReadAllText(file);
			} catch (Exception exp) {
				Log.Add(exp.Message, ConsoleColor.Red);
			}

			if (_content!=null) {
				Parse();
			}
		}

		//переместить точку чтения
		private int Seek(int offset) {
			_index += offset;
			return _index;
		}

		//parsing
		private void Parse() {
			Log.Add(_content, ConsoleColor.White);
		}

		/*
		 * IDisposable
		 */
		private bool disposed = false;

		public void Dispose() {
			Dispose(true);
			//подавляем финализацию
			GC.SuppressFinalize(this);
		}

		protected virtual void Dispose(bool disposing) {
			if (!disposed) {
				if (disposing) {
					// Освобождаем управляемые ресурсы
					_index = 0;
					_content = null;
				}
				// освобождаем неуправляемые объекты
				disposed = true;
			}
		}

	}
}

